---
apiVersion: kots.io/v1beta1
kind: Application
metadata:
  name: mattermost
spec:
  title: Mattermost
  icon: https://raw.githubusercontent.com/cncf/artwork/master/projects/kubernetes/icon/color/kubernetes-icon-color.png
  statusInformers:
    - deployment/mattermost-team-edition
  ports:
    - serviceName: "mattermost"
      servicePort: 80
      localPort: 8888
      applicationUrl: "http://mattermost"
