# values.yaml
# For values.yaml configuration options and examples, refer to the values-example.yaml file.

global:
  # -- Set additional global labels.
  labels: {}
  # -- Set additional global annotations.
  annotations: {}
  # -- Set the full object prefix, defaults to releasName-ChartName if not set. This value takes precedence over nameOverride.
  # Set to "-" to disable object name prefixing.
  fullNameOverride:
  # -- Set an override for the ChartName, defaults to ChartName if not set.
  nameOverride:
  # -- When `true``, the feature to automatically restarts an App pods when a ConfigMap or Secret changes is enabled.
  appReload: true

troubleshoot:
  support-bundles:
    replicated:
      enabled: true
      collectors:
        - clusterInfo: {}
        - clusterResources: {}
        - logs:
            name: example
              # --  Simply use the exact name of application for the appName.
            appName: example
        - logs:
            name: all
              # --  Use the wildcard *, if you wish to select all applications generated by this chart
            appName: "*"
