apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: "vaultwarden"
spec:
  descriptor:
    links:
      - description: Open App
        url: 'http://{{repl ConfigOption "vaultwarden_host" }}'
