apiVersion: cluster.kurl.sh/v1beta1
kind: Installer
metadata:
  name: "installer"
spec:
  kubernetes:
    version: 1.26.x
  containerd:
    version: 1.6.x
  ekco:
    version: latest
  kotsadm:
    version: latest
    disableS3: true
  openebs:
    version: 3.4.x
    isLocalPVEnabled: true
    localPVStorageClassName: local
  prometheus:
    version: 0.63.x
  registry:
    version: 2.8.x
  flannel:
    version: 0.21.x
