apiVersion: v1
data:
  support-bundle-spec: {{ include "support-bundle.spec" . | b64enc }}
kind: Secret
metadata:
  labels:
    troubleshoot.io/kind: support-bundle
  name: {{ .Release.Name }}-support-bundle
  namespace: {{ .Release.Namespace }}
type: Opaque