{{ $cert := genSelfSignedCert "vaultwarden.example.com" nil nil 730 }}
apiVersion: v1
data:
  tls.crt: {{ $cert.Cert | b64enc }}
  tls.key: {{ $cert.Key | b64enc }}
kind: Secret
metadata:
  name: vaultwarden-tls-secret
type: kubernetes.io/tls
