apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: "determined"
spec:
  descriptor:
    links:
      - description: Open App
        url: 'http://{{repl ConfigOption "determined_ingress_host" }}'
