name: Lint and Test Charts

on: pull_request

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.8.1

      # Python is required because `ct lint` runs Yamale (https://github.com/23andMe/Yamale) and
      # yamllint (https://github.com/adrienverge/yamllint) which require Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.2.1
        with:
          version: v3.7.1

      - name: Run chart-testing (lint)
        run: ct lint --config ct.yaml --chart-dirs . --charts .

      - name: Create kind cluster
        uses: helm/kind-action@v1.5.0

      # --skip-clean-up isn't currently released
      #- name: Run chart-testing (install)
      #  id: install
      #  run: ct install --config ct.yaml --chart-dirs . --charts . --skip-clean-up

      # Manually doing install and wait since chart-testing is removing the cluster
      - name: install chart
        id: install
        run: helm install -n default ci . -f values.yaml

      - name: wait for pods
        run: kubectl wait --for=condition=ready -n default po --all --timeout=60s

      - name: wait for pvc
        run: kubectl wait --for=jsonpath='{.status.phase}'=Bound -A pvc --all --timeout=10s

      - name: wait for pv
        run: kubectl wait --for=jsonpath='{.status.phase}'=Bound -A pv --all --timeout=10s

      - name: test chart
        id: test
        run: helm test ci

      - name: install troubleshoot
        run: curl -L https://github.com/replicatedhq/troubleshoot/releases/latest/download/support-bundle_linux_amd64.tar.gz | tar xzvf -
        if: success() || failure()

      - name: collect bundle
        run: ./support-bundle --interactive=false -o ci-bundle https://raw.githubusercontent.com/replicatedhq/troubleshoot-specs/main/host/cluster-down.yaml https://raw.githubusercontent.com/replicatedhq/troubleshoot-specs/main/in-cluster/default.yaml 
        if: success() || failure()

      - name: Upload support bundle artifact
        uses: actions/upload-artifact@v3
        if: success() || failure()
        with:
          name: support-bundle
          path: 'ci-bundle.tar.gz'
